fix: Audit service fix for multiple spring tasklets
hmcts/rd-judicial-data-load pull request #155
Opened 2020-12-03 17:56 UTC by abhijitdiwan

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-2086

### Change description ###
fix: Audit service fix for multiple spring tasklets 

**Does this PR introduce a breaking change?** (check one with "x")
No

2020-12-03 18:15 UTC, shashank-rastogi approved these changes

2020-12-07 17:51 UTC, shashank-rastogi requested changes

2020-12-08 11:28 UTC, abhijitdiwan commented on build.gradle
>      }
removed

2020-12-08 11:28 UTC, abhijitdiwan commented on build.gradle
done

2020-12-08 12:38 UTC, shashank-rastogi approved these changes

2020-12-08 12:38 UTC, shreedhar-hmcts approved these changes

2020-12-08 12:39 UTC, merged